name: educativa_application_interculturalidad
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  firebase_core: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background/bck.jpg
    - assets/imgs/play.png
    - assets/imgs/perro.png
    - 'assets/imgs/leon.png'
    - assets/background/bck2.jpg
    - assets/imgs/sierra.jpg
    - assets/imgs/costa.png
    - assets/imgs/Sierra/caballo.png
    - assets/imgs/Sierra/cabra.png
    - assets/imgs/Sierra/cerdito.png
    - assets/imgs/Sierra/gallo.png
    - assets/imgs/Sierra/oveja.png
    - assets/imgs/Sierra/perro.png
    - assets/imgs/costa/mono.png 
    - assets/imgs/costa/rana.png
    - assets/imgs/costa/serpiente.png
    - assets/imgs/costa/tortuga.png
    - assets/imgs/costa/tucan.png
    - assets/imgs/costa/zorra.png
    - assets/sounds/cabra.mp3
    - assets/sounds/cerdo.mp3
    - assets/sounds/caballo.mp3
    - assets/sounds/gallo.mp3
    - assets/sounds/oveja.mp3
    - assets/sounds/perro.mp3
    - assets/sounds/tucan.mp3
    - assets/sounds/serpiente.mp3
    - assets/sounds/zorra.mp3

    - assets/sounds/mono.mp3
    - assets/sounds/rana.mp3
    - assets/sounds/serpiente.mp3
    - assets/sounds/tucan.mp3
    - assets/sounds/zorra.mp3