// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnFtdbDUc9xL52y-747HKt2-Hs1Qu7dsc',
    appId: '1:330092439678:web:65a25489ed9dee45bc102f',
    messagingSenderId: '330092439678',
    projectId: 'interculturalidad-13249',
    authDomain: 'interculturalidad-13249.firebaseapp.com',
    storageBucket: 'interculturalidad-13249.firebasestorage.app',
    measurementId: 'G-HDPS5NPTBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt-yi1sihy0_acrj-dv1W_BwFjJ2IyFkE',
    appId: '1:330092439678:android:32930ace2290d7d8bc102f',
    messagingSenderId: '330092439678',
    projectId: 'interculturalidad-13249',
    storageBucket: 'interculturalidad-13249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-aF70n8Tm7NsNGyNPJmLQYsbFOAe-eGw',
    appId: '1:330092439678:ios:b0ab6640e8fb7e71bc102f',
    messagingSenderId: '330092439678',
    projectId: 'interculturalidad-13249',
    storageBucket: 'interculturalidad-13249.firebasestorage.app',
    iosBundleId: 'com.example.educativaApplicationInterculturalidad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-aF70n8Tm7NsNGyNPJmLQYsbFOAe-eGw',
    appId: '1:330092439678:ios:b0ab6640e8fb7e71bc102f',
    messagingSenderId: '330092439678',
    projectId: 'interculturalidad-13249',
    storageBucket: 'interculturalidad-13249.firebasestorage.app',
    iosBundleId: 'com.example.educativaApplicationInterculturalidad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnFtdbDUc9xL52y-747HKt2-Hs1Qu7dsc',
    appId: '1:330092439678:web:d29fac6b728859debc102f',
    messagingSenderId: '330092439678',
    projectId: 'interculturalidad-13249',
    authDomain: 'interculturalidad-13249.firebaseapp.com',
    storageBucket: 'interculturalidad-13249.firebasestorage.app',
    measurementId: 'G-9073SWF35G',
  );
}
